// State data with major city and timezone for each state
export const stateData = [
  { name: 'Alabama', abbr: 'AL', city: 'Birmingham', timezone: 'America/Chicago' },
  { name: 'Alaska', abbr: 'AK', city: 'Anchorage', timezone: 'America/Anchorage' },
  { name: 'Arizona', abbr: 'AZ', city: 'Phoenix', timezone: 'America/Phoenix' },
  { name: 'Arkansas', abbr: 'AR', city: 'Little Rock', timezone: 'America/Chicago' },
  { name: 'California', abbr: 'CA', city: 'Los Angeles', timezone: 'America/Los_Angeles' },
  { name: 'Colorado', abbr: 'CO', city: 'Denver', timezone: 'America/Denver' },
  { name: 'Connecticut', abbr: 'CT', city: 'Hartford', timezone: 'America/New_York' },
  { name: 'Delaware', abbr: 'DE', city: 'Dover', timezone: 'America/New_York' },
  { name: 'Florida', abbr: 'FL', city: 'Miami', timezone: 'America/New_York' },
  { name: 'Georgia', abbr: 'GA', city: 'Atlanta', timezone: 'America/New_York' },
  { name: 'Hawaii', abbr: 'HI', city: 'Honolulu', timezone: 'Pacific/Honolulu' },
  { name: 'Idaho', abbr: 'ID', city: 'Boise', timezone: 'America/Boise' },
  { name: 'Illinois', abbr: 'IL', city: 'Chicago', timezone: 'America/Chicago' },
  { name: 'Indiana', abbr: 'IN', city: 'Indianapolis', timezone: 'America/Indiana/Indianapolis' },
  { name: 'Iowa', abbr: 'IA', city: 'Des Moines', timezone: 'America/Chicago' },
  { name: 'Kansas', abbr: 'KS', city: 'Wichita', timezone: 'America/Chicago' },
  { name: 'Kentucky', abbr: 'KY', city: 'Louisville', timezone: 'America/Kentucky/Louisville' },
  { name: 'Louisiana', abbr: 'LA', city: 'New Orleans', timezone: 'America/Chicago' },
  { name: 'Maine', abbr: 'ME', city: 'Portland', timezone: 'America/New_York' },
  { name: 'Maryland', abbr: 'MD', city: 'Baltimore', timezone: 'America/New_York' },
  { name: 'Massachusetts', abbr: 'MA', city: 'Boston', timezone: 'America/New_York' },
  { name: 'Michigan', abbr: 'MI', city: 'Detroit', timezone: 'America/Detroit' },
  { name: 'Minnesota', abbr: 'MN', city: 'Minneapolis', timezone: 'America/Chicago' },
  { name: 'Mississippi', abbr: 'MS', city: 'Jackson', timezone: 'America/Chicago' },
  { name: 'Missouri', abbr: 'MO', city: 'Kansas City', timezone: 'America/Chicago' },
  { name: 'Montana', abbr: 'MT', city: 'Billings', timezone: 'America/Denver' },
  { name: 'Nebraska', abbr: 'NE', city: 'Omaha', timezone: 'America/Chicago' },
  { name: 'Nevada', abbr: 'NV', city: 'Las Vegas', timezone: 'America/Los_Angeles' },
  { name: 'New Hampshire', abbr: 'NH', city: 'Manchester', timezone: 'America/New_York' },
  { name: 'New Jersey', abbr: 'NJ', city: 'Newark', timezone: 'America/New_York' },
  { name: 'New Mexico', abbr: 'NM', city: 'Albuquerque', timezone: 'America/Denver' },
  { name: 'New York', abbr: 'NY', city: 'New York City', timezone: 'America/New_York' },
  { name: 'North Carolina', abbr: 'NC', city: 'Charlotte', timezone: 'America/New_York' },
  { name: 'North Dakota', abbr: 'ND', city: 'Fargo', timezone: 'America/Chicago' },
  { name: 'Ohio', abbr: 'OH', city: 'Columbus', timezone: 'America/New_York' },
  { name: 'Oklahoma', abbr: 'OK', city: 'Oklahoma City', timezone: 'America/Chicago' },
  { name: 'Oregon', abbr: 'OR', city: 'Portland', timezone: 'America/Los_Angeles' },
  { name: 'Pennsylvania', abbr: 'PA', city: 'Philadelphia', timezone: 'America/New_York' },
  { name: 'Rhode Island', abbr: 'RI', city: 'Providence', timezone: 'America/New_York' },
  { name: 'South Carolina', abbr: 'SC', city: 'Charleston', timezone: 'America/New_York' },
  { name: 'South Dakota', abbr: 'SD', city: 'Sioux Falls', timezone: 'America/Chicago' },
  { name: 'Tennessee', abbr: 'TN', city: 'Nashville', timezone: 'America/Chicago' },
  { name: 'Texas', abbr: 'TX', city: 'Houston', timezone: 'America/Chicago' },
  { name: 'Utah', abbr: 'UT', city: 'Salt Lake City', timezone: 'America/Denver' },
  { name: 'Vermont', abbr: 'VT', city: 'Burlington', timezone: 'America/New_York' },
  { name: 'Virginia', abbr: 'VA', city: 'Richmond', timezone: 'America/New_York' },
  { name: 'Washington', abbr: 'WA', city: 'Seattle', timezone: 'America/Los_Angeles' },
  { name: 'West Virginia', abbr: 'WV', city: 'Charleston', timezone: 'America/New_York' },
  { name: 'Wisconsin', abbr: 'WI', city: 'Milwaukee', timezone: 'America/Chicago' },
  { name: 'Wyoming', abbr: 'WY', city: 'Cheyenne', timezone: 'America/Denver' }
];
